---
title: "Appendix A3 - Removal of particles in the chamber by the ESP"
output: html_notebook
---



```{r setup}

source("utilities.R")
source("variables.R")
require(ggplot2)
require(plotly)
require(splitstackshape)
require(cowplot)
require(forcats)

df <-prepare_sensor_data(sensor_raw_file, cdt)


dt <- readRDS("C:/Data/LabStudy/20190826LimitOfDetection/ref/dusttrak_limitofdetection_26082019.Rds")
ops<-readRDS("C:/Data/LabStudy/20190826LimitOfDetection/ref/2019_08_26-14_53_29-TEST_001.Rds")


x<-factor(cdt$exp)
#cdt$exp<-fct_recode(x, "(1) RH=54%" = "RH55 T23C 05092019 No Enclosure", "(2) RH=68%" = "RH75 T23C 05092019 No Enclosure", "(3) RH=72%" ="RH80 T23C 05092019 No Enclosure", "(4) RH=75%" = "RH85 T23C 05092019 No Enclosure", "(5) RH=79%" = "RH90 T23C 05092019 No Enclosure") 

df <- df %>%
  flag_cdt_data(cdt) %>%
  filter(exp != "")

df<- df %>% mutate(sensor_site = paste0(site,"_", sensor))
df2<-cSplit(indt=df,splitCols = c("sensor"),sep="-",direction="wide",drop=FALSE)
df2 %>%
  select(-sensor_2,-sensor_3)->df



dt <- dt %>%
  flag_cdt_data(cdt)# %>%
 # filter(exp!="")

ops<- readRDS(file = ops_file) 


ops<-ops %>%
  flag_cdt_data(cdt)#%>%   
 # filter(exp!="")
nanotracer <- readRDS(nanotracer_file) %>%
  flag_cdt_data(cdt) #%>%
 #   filter(exp!="")





```


# (1) RH=54%


```{r}


dt_exp <- dt %>%
 filter(date_time>=as.POSIXct("2019-08-26 12:55:00", tz = "UTC") & date_time <= as.POSIXct("2019-08-26 13:20:00", tz = "UTC"))

ops_exp<- ops %>% 
  filter(date_time >= min(dt_exp$date_time), date_time<=max(dt_exp$date_time))

p_ops_3<-ops_exp %>%
  gather(bin_name, bin_count, starts_with("Bin.")) %>%
  filter(bin_name %in% c("Bin.1", "Bin.2", "Bin.3")) %>%
  ggplot() +
  geom_line(aes(x=date_time, y= bin_count, color=bin_name, group=bin_name))+ylab("Number of particles (#/cm3)") + scale_colour_manual(values = c("#1B9E77", "#D95F02", "#7570B3"))+
  theme_bw() #+  
 # theme(panel.spacing = unit(0, "lines")) +
 # theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_ops_4_7<-ops_exp %>%
  gather(bin_name, bin_count, starts_with("Bin.")) %>%
  filter(bin_name %in% c("Bin.4", "Bin.5", "Bin.6", "Bin.7")) %>%
  ggplot() +
  geom_line(aes(x=date_time, y= bin_count, color=bin_name, group=bin_name))+ylab("Number of particles (#/cm3)")+ scale_colour_manual(values = c("#E7298A", "#66A61E", "#E6AB02", "#A6761D"))+
  theme_bw()#+  
 # theme(panel.spacing = unit(0, "lines")) +
 # theme(plot.margin = unit(c(0,0,0,0), "lines"))




p_dt<-ggplot()+geom_line(data = dt_exp, aes(x = date_time,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + xlab("Time")+theme_bw()# +  
 # theme(panel.spacing = unit(0, "lines")) +
 # theme(plot.margin = unit(c(0,0,0,0), "lines"))



legend_ops_3 <- get_legend(p_ops_3)
legend_ops_4_7 <- get_legend(p_ops_4_7)

legend_p_dt <- get_legend(p_dt)


label_ops_3<-p_ops_3$labels$y
label_ops_4_7 <-p_ops_4_7$labels$y
label_p_dt <- p_dt$labels$y


p_ops_3 <- p_ops_3+
  theme(legend.position = "none") + 
  theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_ops_4_7 <- p_ops_4_7+
  theme(legend.position = "none") + 
  theme(axis.title.x=element_blank(), axis.title.y=element_blank())



p_dt <- p_dt+
  theme(legend.position = "none")+ 
  theme(axis.title.y=element_blank())



pl_assembled<-plot_grid(p_ops_3, p_ops_4_7, 
             p_dt,
             nrow=3, align = "v", rel_heights = c(0.25, 0.25, 0.25)
             , labels=c("(a)", "(b)", "(c)"),label_size = 10 )

pl_assembled

ggsave(pl_assembled, filename = "esp_performances.svg", height = 10, width = 8)

pl_assembled_legend <- plot_grid(legend_ops_3)

ggsave(pl_assembled_legend, filename = "time_series_no_enclosure_exp_1_legend.svg", height = 14, width = 8)

```


```{r}

df <-prepare_sensor_data(sensor_raw_file, cdt)


dt <- prepare_dusttrak_data(dusttrak_file, cdt) 



x<-factor(cdt$exp)
#cdt$exp<-fct_recode(x, "(1) RH=54%" = "RH55 T23C 05092019 No Enclosure", "(2) RH=68%" = "RH75 T23C 05092019 No Enclosure", "(3) RH=72%" ="RH80 T23C 05092019 No Enclosure", "(4) RH=75%" = "RH85 T23C 05092019 No Enclosure", "(5) RH=79%" = "RH90 T23C 05092019 No Enclosure") 

df <- df %>%
  flag_cdt_data(cdt) %>%
  filter(exp != "")

df<- df %>% mutate(sensor_site = paste0(site,"_", sensor))
df2<-cSplit(indt=df,splitCols = c("sensor"),sep="-",direction="wide",drop=FALSE)
df2 %>%
  select(-sensor_2,-sensor_3)->df



dt <- dt %>%
  flag_cdt_data(cdt) %>%
  filter(exp!="")

ops<- readRDS(file = ops_file) %>%
  flag_cdt_data(cdt) %>%   
  filter(exp!="")
nanotracer <- readRDS(nanotracer_file) %>%
  flag_cdt_data(cdt) %>%
    filter(exp!="")





```


```{r}

dt_exp <- dt %>%
 filter(date_time>=as.POSIXct("2019-08-26 12:55:00", tz = "UTC") & date_time <= as.POSIXct("2019-08-26 13:20:00", tz = "UTC"))

ops_exp<- ops %>% 
  filter(date_time >= min(dt_exp$date_time), date_time<=max(dt_exp$date_time))

p_ops_3<-ops_exp %>%
  gather(bin_name, bin_count, starts_with("Bin.")) %>%
  filter(bin_name %in% c("Bin.1", "Bin.2", "Bin.3")) %>%
  ggplot() +
  geom_line(aes(x=date_time, y= bin_count, color=bin_name, group=bin_name))+ylab("Number of particles (#/cm3)") + scale_colour_manual(values = c("#1B9E77", "#D95F02", "#7570B3"))+
  theme_bw() #+  
 # theme(panel.spacing = unit(0, "lines")) +
 # theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_ops_4_7<-ops_exp %>%
  gather(bin_name, bin_count, starts_with("Bin.")) %>%
  filter(bin_name %in% c("Bin.4", "Bin.5", "Bin.6", "Bin.7")) %>%
  ggplot() +
  geom_line(aes(x=date_time, y= bin_count, color=bin_name, group=bin_name))+ylab("Number of particles (#/cm3)")+ scale_colour_manual(values = c("#E7298A", "#66A61E", "#E6AB02", "#A6761D"))+
  theme_bw()#+  
 # theme(panel.spacing = unit(0, "lines")) +
 # theme(plot.margin = unit(c(0,0,0,0), "lines"))




p_dt<-ggplot()+geom_line(data = dt_exp, aes(x = date_time,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + xlab("Time")+theme_bw()# +  
 # theme(panel.spacing = unit(0, "lines")) +
 # theme(plot.margin = unit(c(0,0,0,0), "lines"))



legend_ops_3 <- get_legend(p_ops_3)
legend_ops_4_7 <- get_legend(p_ops_4_7)

legend_p_dt <- get_legend(p_dt)


label_ops_3<-p_ops_3$labels$y
label_ops_4_7 <-p_ops_4_7$labels$y
label_p_dt <- p_dt$labels$y


p_ops_3 <- p_ops_3+
  theme(legend.position = "none") + 
  theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_ops_4_7 <- p_ops_4_7+
  theme(legend.position = "none") + 
  theme(axis.title.x=element_blank(), axis.title.y=element_blank())



p_dt <- p_dt+
  theme(legend.position = "none")+ 
  theme(axis.title.y=element_blank())



pl_assembled<-plot_grid(p_ops_3, p_ops_4_7, 
             p_dt,
             nrow=3, align = "v", rel_heights = c(0.25, 0.25, 0.25)
             , labels=c("(a)", "(b)", "(c)"),label_size = 10 )

pl_assembled



```

