---
title: "Figure 4 - time series"
output: html_notebook
---



```{r setup}

source("utilities.R")
source("variables.R")
require(ggplot2)
require(plotly)
require(splitstackshape)
require(cowplot)
require(forcats)

df <-prepare_sensor_data(sensor_raw_file, cdt)


dt <- prepare_dusttrak_data(dusttrak_file, cdt) 



x<-factor(cdt$exp)
#cdt$exp<-fct_recode(x, "(1) RH=54%" = "RH55 T23C 05092019 No Enclosure", "(2) RH=68%" = "RH75 T23C 05092019 No Enclosure", "(3) RH=72%" ="RH80 T23C 05092019 No Enclosure", "(4) RH=75%" = "RH85 T23C 05092019 No Enclosure", "(5) RH=79%" = "RH90 T23C 05092019 No Enclosure") 

df <- df %>%
  flag_cdt_data(cdt) %>%
  filter(exp != "")

df<- df %>% mutate(sensor_site = paste0(site,"_", sensor))
df2<-cSplit(indt=df,splitCols = c("sensor"),sep="-",direction="wide",drop=FALSE)
df2 %>%
  select(-sensor_2,-sensor_3)->df



dt <- dt %>%
  flag_cdt_data(cdt) %>%
  filter(exp!="")

ops<- readRDS(file = ops_file) %>%
  flag_cdt_data(cdt) %>%   
  filter(exp!="")
nanotracer <- readRDS(nanotracer_file) %>%
  flag_cdt_data(cdt) %>%
    filter(exp!="")





```


# (1) RH=54%


```{r}

df_exp <- df %>%
  filter(exp == "(1) RH=54%") %>%
  ungroup()


dt_exp <- dt %>%
  filter(exp == "(1) RH=54%")

ops_exp<- ops %>% 
  filter(date >= min(df_exp$date), date<=max(df_exp$date))
nanotracer_exp <- nanotracer%>% 
  filter(date >= min(df_exp$date), date<=max(df_exp$date))


p_ops_3<-ops_exp %>%
  gather(bin_name, bin_count, starts_with("Bin.")) %>%
  filter(bin_name %in% c("Bin.1", "Bin.2", "Bin.3")) %>%
  ggplot() +
  geom_line(aes(x=date, y= bin_count, color=bin_name, group=bin_name))+ylab("Number of particles (#/cm3)") + scale_colour_manual(values = c("#1B9E77", "#D95F02", "#7570B3"))+theme_bw() +facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_ops_4_7<-ops_exp %>%
  gather(bin_name, bin_count, starts_with("Bin.")) %>%
  filter(bin_name %in% c("Bin.4", "Bin.5", "Bin.6", "Bin.7")) %>%
  ggplot() +
  geom_line(aes(x=date, y= bin_count, color=bin_name, group=bin_name))+ylab("Number of particles (#/cm3)")+ scale_colour_manual(values = c("#E7298A", "#66A61E", "#E6AB02", "#A6761D"))+theme_bw() +facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_nano<-nanotracer_exp %>%
  ggplot() +
  geom_line(aes(x=date, y = N.1.))+ylab("Ultrafine particles number (#/cm3)")+theme_bw() +facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))


p_pms<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "PMS5003"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Plantower PMS5003") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_opcr1<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "OPCR1"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Alphasense OPCR1") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_sps<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "SPS030"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Sensirion SPS030") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_sds<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "SDS018"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Novafitness SDS018") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_hpma<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "HPMA115S0"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Honeywell HPMA115S0") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

legend_ops_3 <- get_legend(p_ops_3)
legend_ops_4_7 <- get_legend(p_ops_4_7)

legend_p_pms <- get_legend(p_pms)
legend_p_opcr1 <- get_legend(p_opcr1)
legend_p_sps <- get_legend(p_sps)
legend_p_sds <- get_legend(p_sds)
legend_p_hpma <- get_legend(p_hpma)

label_ops_3<-p_ops_3$labels$y
label_ops_4_7 <-p_ops_4_7$labels$y
label_p_pms <- p_pms$labels$y


p_ops_3 <- p_ops_3+theme(legend.position = "none") + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_ops_4_7 <- p_ops_4_7+theme(legend.position = "none") + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_nano <- p_nano+theme(legend.position = "none") + theme(axis.title.x=element_blank(), axis.title.y=element_blank())


p_pms <- p_pms+theme(legend.position = "none")+ theme(axis.title.y=element_blank())
p_opcr1 <- p_opcr1+theme(legend.position = "none")+ theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_sps <- p_sps+theme(legend.position = "none")+ theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_sds <- p_sds+theme(legend.position = "none")+ theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_hpma <- p_hpma+theme(legend.position = "none")+ theme(axis.title.x=element_blank(), axis.title.y=element_blank())


pl_assembled<-plot_grid(p_ops_3, p_ops_4_7, p_nano, 
             p_hpma, p_opcr1,p_sds,p_sps, p_pms,
             nrow=8, align = "v", rel_heights = c(0.2, 0.2, 0.2, 0.4, 0.4, 0.4, 0.4,0.4)
             , labels=c("(a)", "(b)", "(c)", "(d)", "(e)", "(f)", "(g)", "(h)"),label_size = 10 )

pl_assembled
pl_assembled_legend<-plot_grid(legend_ops_3, legend_ops_4_7, legend_p_hpma, legend_p_opcr1, legend_p_sds, legend_p_sps, legend_p_pms,nrow=3,ncol=3 )


#ggsave(pl_assembled,filename = "time_series_no_enclosure_exp_1.svg", height = 14, width = 8)

pl_assembled_legend
#ggsave(pl_assembled_legend, filename = "time_series_no_enclosure_exp_1_legend.svg", height = 14, width = 8)

```

# (2) RH=68%

```{r}

df_exp <- df %>%
  filter(exp == "(2) RH=68%") %>%
  ungroup()


dt_exp <- dt %>%
  filter(exp == "(2) RH=68%")

ops_exp<- ops %>% 
  filter(date >= min(df_exp$date), date<=max(df_exp$date))
nanotracer_exp <- nanotracer%>% 
  filter(date >= min(df_exp$date), date<=max(df_exp$date))


p_ops_3<-ops_exp %>%
  gather(bin_name, bin_count, starts_with("Bin.")) %>%
  filter(bin_name %in% c("Bin.1", "Bin.2", "Bin.3")) %>%
  ggplot() +
  geom_line(aes(x=date, y= bin_count, color=bin_name, group=bin_name))+ylab("Number of particles (#/cm3)") + scale_colour_manual(values = c("#1B9E77", "#D95F02", "#7570B3"))+theme_bw() +facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_ops_4_7<-ops_exp %>%
  gather(bin_name, bin_count, starts_with("Bin.")) %>%
  filter(bin_name %in% c("Bin.4", "Bin.5", "Bin.6", "Bin.7")) %>%
  ggplot() +
  geom_line(aes(x=date, y= bin_count, color=bin_name, group=bin_name))+ylab("Number of particles (#/cm3)")+ scale_colour_manual(values = c("#E7298A", "#66A61E", "#E6AB02", "#A6761D"))+theme_bw() +facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_nano<-nanotracer_exp %>%
  ggplot() +
  geom_line(aes(x=date, y = N.1.))+ylab("Ultrafine particles number (#/cm3)")+theme_bw() +facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))


p_pms<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "PMS5003"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Plantower PMS5003") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_opcr1<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "OPCR1"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Alphasense OPCR1") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_sps<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "SPS030"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Sensirion SPS030") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_sds<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "SDS018"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Novafitness SDS018") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_hpma<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "HPMA115S0"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Honeywell HPMA115S0") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

legend_ops_3 <- get_legend(p_ops_3)
legend_ops_4_7 <- get_legend(p_ops_4_7)

legend_p_pms <- get_legend(p_pms)
legend_p_opcr1 <- get_legend(p_opcr1)
legend_p_sps <- get_legend(p_sps)
legend_p_sds <- get_legend(p_sds)
legend_p_hpma <- get_legend(p_hpma)

label_ops_3<-p_ops_3$labels$y
label_ops_4_7 <-p_ops_4_7$labels$y
label_p_pms <- p_pms$labels$y


p_ops_3 <- p_ops_3+theme(legend.position = "none") + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_ops_4_7 <- p_ops_4_7+theme(legend.position = "none") + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_nano <- p_nano+theme(legend.position = "none") + theme(axis.title.x=element_blank(), axis.title.y=element_blank())


p_pms <- p_pms+theme(legend.position = "none")+ theme(axis.title.y=element_blank())
p_opcr1 <- p_opcr1+theme(legend.position = "none")+ theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_sps <- p_sps+theme(legend.position = "none")+ theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_sds <- p_sds+theme(legend.position = "none")+ theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_hpma <- p_hpma+theme(legend.position = "none")+ theme(axis.title.x=element_blank(), axis.title.y=element_blank())


pl_assembled<-plot_grid(p_ops_3, p_ops_4_7, p_nano, 
             p_hpma, p_opcr1,p_sds,p_sps, p_pms,
             nrow=8, align = "v", rel_heights = c(0.2, 0.2, 0.2, 0.4, 0.4, 0.4, 0.4,0.4)
             , labels=c("(a)", "(b)", "(c)", "(d)", "(e)", "(f)", "(g)", "(h)"),label_size = 10 )

pl_assembled
pl_assembled_legend<-plot_grid(legend_ops_3, legend_ops_4_7, legend_p_hpma, legend_p_opcr1, legend_p_sds, legend_p_sps, legend_p_pms,nrow=3,ncol=3 )


ggsave(pl_assembled,filename = "time_series_no_enclosure_exp_2.svg", height = 14, width = 8)

pl_assembled_legend
ggsave(pl_assembled_legend, filename = "time_series_no_enclosure_exp_2_legend.svg", height = 14, width = 8)
```


# (3) RH=72%

```{r}


df_exp <- df %>%
  filter(exp == "(3) RH=72%") %>%
  ungroup()


dt_exp <- dt %>%
  filter(exp == "(3) RH=72%")

ops_exp<- ops %>% 
  filter(date >= min(df_exp$date), date<=max(df_exp$date))
nanotracer_exp <- nanotracer%>% 
  filter(date >= min(df_exp$date), date<=max(df_exp$date))


p_ops_3<-ops_exp %>%
  gather(bin_name, bin_count, starts_with("Bin.")) %>%
  filter(bin_name %in% c("Bin.1", "Bin.2", "Bin.3")) %>%
  ggplot() +
  geom_line(aes(x=date, y= bin_count, color=bin_name, group=bin_name))+ylab("Number of particles (#/cm3)") + scale_colour_manual(values = c("#1B9E77", "#D95F02", "#7570B3"))+theme_bw() +facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_ops_4_7<-ops_exp %>%
  gather(bin_name, bin_count, starts_with("Bin.")) %>%
  filter(bin_name %in% c("Bin.4", "Bin.5", "Bin.6", "Bin.7")) %>%
  ggplot() +
  geom_line(aes(x=date, y= bin_count, color=bin_name, group=bin_name))+ylab("Number of particles (#/cm3)")+ scale_colour_manual(values = c("#E7298A", "#66A61E", "#E6AB02", "#A6761D"))+theme_bw() +facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_nano<-nanotracer_exp %>%
  ggplot() +
  geom_line(aes(x=date, y = N.1.))+ylab("Ultrafine particles number (#/cm3)")+theme_bw() +facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))


p_pms<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "PMS5003"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Plantower PMS5003") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_opcr1<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "OPCR1"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Alphasense OPCR1") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_sps<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "SPS030"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Sensirion SPS030") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_sds<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "SDS018"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Novafitness SDS018") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_hpma<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "HPMA115S0"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Honeywell HPMA115S0") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

legend_ops_3 <- get_legend(p_ops_3)
legend_ops_4_7 <- get_legend(p_ops_4_7)

legend_p_pms <- get_legend(p_pms)
legend_p_opcr1 <- get_legend(p_opcr1)
legend_p_sps <- get_legend(p_sps)
legend_p_sds <- get_legend(p_sds)
legend_p_hpma <- get_legend(p_hpma)

label_ops_3<-p_ops_3$labels$y
label_ops_4_7 <-p_ops_4_7$labels$y
label_p_pms <- p_pms$labels$y


p_ops_3 <- p_ops_3+theme(legend.position = "none") + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_ops_4_7 <- p_ops_4_7+theme(legend.position = "none") + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_nano <- p_nano+theme(legend.position = "none") + theme(axis.title.x=element_blank(), axis.title.y=element_blank())


p_pms <- p_pms+theme(legend.position = "none")+ theme(axis.title.y=element_blank())
p_opcr1 <- p_opcr1+theme(legend.position = "none")+ theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_sps <- p_sps+theme(legend.position = "none")+ theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_sds <- p_sds+theme(legend.position = "none")+ theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_hpma <- p_hpma+theme(legend.position = "none")+ theme(axis.title.x=element_blank(), axis.title.y=element_blank())


pl_assembled<-plot_grid(p_ops_3, p_ops_4_7, p_nano, 
             p_hpma, p_opcr1,p_sds,p_sps, p_pms,
             nrow=8, align = "v", rel_heights = c(0.2, 0.2, 0.2, 0.4, 0.4, 0.4, 0.4,0.4)
             , labels=c("(a)", "(b)", "(c)", "(d)", "(e)", "(f)", "(g)", "(h)"),label_size = 10 )

pl_assembled
pl_assembled_legend<-plot_grid(legend_ops_3, legend_ops_4_7, legend_p_hpma, legend_p_opcr1, legend_p_sds, legend_p_sps, legend_p_pms,nrow=3,ncol=3 )


ggsave(pl_assembled,filename = "time_series_no_enclosure_exp_3.svg", height = 14, width = 8)

pl_assembled_legend
ggsave(pl_assembled_legend, filename = "time_series_no_enclosure_exp_3_legend.svg", height = 14, width = 8)

```


# (4) RH=75%

```{r}


df_exp <- df %>%
  filter(exp == "(4) RH=75%") %>%
  ungroup()


dt_exp <- dt %>%
  filter(exp == "(4) RH=75%")

ops_exp<- ops %>% 
  filter(date >= min(df_exp$date), date<=max(df_exp$date))
nanotracer_exp <- nanotracer%>% 
  filter(date >= min(df_exp$date), date<=max(df_exp$date))


p_ops_3<-ops_exp %>%
  gather(bin_name, bin_count, starts_with("Bin.")) %>%
  filter(bin_name %in% c("Bin.1", "Bin.2", "Bin.3")) %>%
  ggplot() +
  geom_line(aes(x=date, y= bin_count, color=bin_name, group=bin_name))+ylab("Number of particles (#/cm3)") + scale_colour_manual(values = c("#1B9E77", "#D95F02", "#7570B3"))+theme_bw() +facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_ops_4_7<-ops_exp %>%
  gather(bin_name, bin_count, starts_with("Bin.")) %>%
  filter(bin_name %in% c("Bin.4", "Bin.5", "Bin.6", "Bin.7")) %>%
  ggplot() +
  geom_line(aes(x=date, y= bin_count, color=bin_name, group=bin_name))+ylab("Number of particles (#/cm3)")+ scale_colour_manual(values = c("#E7298A", "#66A61E", "#E6AB02", "#A6761D"))+theme_bw() +facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_nano<-nanotracer_exp %>%
  ggplot() +
  geom_line(aes(x=date, y = N.1.))+ylab("Ultrafine particles number (#/cm3)")+theme_bw() +facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))


p_pms<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "PMS5003"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Plantower PMS5003") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_opcr1<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "OPCR1"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Alphasense OPCR1") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_sps<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "SPS030"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Sensirion SPS030") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_sds<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "SDS018"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Novafitness SDS018") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_hpma<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "HPMA115S0"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Honeywell HPMA115S0") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

legend_ops_3 <- get_legend(p_ops_3)
legend_ops_4_7 <- get_legend(p_ops_4_7)

legend_p_pms <- get_legend(p_pms)
legend_p_opcr1 <- get_legend(p_opcr1)
legend_p_sps <- get_legend(p_sps)
legend_p_sds <- get_legend(p_sds)
legend_p_hpma <- get_legend(p_hpma)

label_ops_3<-p_ops_3$labels$y
label_ops_4_7 <-p_ops_4_7$labels$y
label_p_pms <- p_pms$labels$y


p_ops_3 <- p_ops_3+theme(legend.position = "none") + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_ops_4_7 <- p_ops_4_7+theme(legend.position = "none") + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_nano <- p_nano+theme(legend.position = "none") + theme(axis.title.x=element_blank(), axis.title.y=element_blank())


p_pms <- p_pms+theme(legend.position = "none")+ theme(axis.title.y=element_blank())
p_opcr1 <- p_opcr1+theme(legend.position = "none")+ theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_sps <- p_sps+theme(legend.position = "none")+ theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_sds <- p_sds+theme(legend.position = "none")+ theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_hpma <- p_hpma+theme(legend.position = "none")+ theme(axis.title.x=element_blank(), axis.title.y=element_blank())


pl_assembled<-plot_grid(p_ops_3, p_ops_4_7, p_nano, 
             p_hpma, p_opcr1,p_sds,p_sps, p_pms,
             nrow=8, align = "v", rel_heights = c(0.2, 0.2, 0.2, 0.4, 0.4, 0.4, 0.4,0.4)
             , labels=c("(a)", "(b)", "(c)", "(d)", "(e)", "(f)", "(g)", "(h)"),label_size = 10 )

pl_assembled
pl_assembled_legend<-plot_grid(legend_ops_3, legend_ops_4_7, legend_p_hpma, legend_p_opcr1, legend_p_sds, legend_p_sps, legend_p_pms,nrow=3,ncol=3 )


ggsave(pl_assembled,filename = "time_series_no_enclosure_exp_4.svg", height = 14, width = 8)

pl_assembled_legend
ggsave(pl_assembled_legend, filename = "time_series_no_enclosure_exp_4_legend.svg", height = 14, width = 8)

```


# (5) RH=79%

```{r}

df_exp <- df %>%
  filter(exp == "(5) RH=79%") %>%
  ungroup()


dt_exp <- dt %>%
  filter(exp == "(5) RH=79%")

ops_exp<- ops %>% 
  filter(date >= min(df_exp$date), date<=max(df_exp$date))
nanotracer_exp <- nanotracer%>% 
  filter(date >= min(df_exp$date), date<=max(df_exp$date))


p_ops_3<-ops_exp %>%
  gather(bin_name, bin_count, starts_with("Bin.")) %>%
  filter(bin_name %in% c("Bin.1", "Bin.2", "Bin.3")) %>%
  ggplot() +
  geom_line(aes(x=date, y= bin_count, color=bin_name, group=bin_name))+ylab("Number of particles (#/cm3)") + scale_colour_manual(values = c("#1B9E77", "#D95F02", "#7570B3"))+theme_bw() +facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_ops_4_7<-ops_exp %>%
  gather(bin_name, bin_count, starts_with("Bin.")) %>%
  filter(bin_name %in% c("Bin.4", "Bin.5", "Bin.6", "Bin.7")) %>%
  ggplot() +
  geom_line(aes(x=date, y= bin_count, color=bin_name, group=bin_name))+ylab("Number of particles (#/cm3)")+ scale_colour_manual(values = c("#E7298A", "#66A61E", "#E6AB02", "#A6761D"))+theme_bw() +facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_nano<-nanotracer_exp %>%
  ggplot() +
  geom_line(aes(x=date, y = N.1.))+ylab("Ultrafine particles number (#/cm3)")+theme_bw() +facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))


p_pms<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "PMS5003"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Plantower PMS5003") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_opcr1<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "OPCR1"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Alphasense OPCR1") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_sps<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "SPS030"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Sensirion SPS030") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_sds<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "SDS018"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Novafitness SDS018") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

p_hpma<-ggplot()+
         geom_line(data = filter(df_exp, sensor_1== "HPMA115S0"),
                 aes(x = date, y = PM25, group = sensor_site, colour = sensor_site, 
                     text = paste0("Box: ", site,
                                   "<br>Exp: ", exp,
                                  "<br>Source: ", source))) +
        labs(y = "PM2.5 (ug/m3)") +
        geom_line(data = dt_exp, aes(x = date,y = pm2.5), colour = "red", linetype = "dashed")+
        scale_x_datetime() + theme_bw() + ggtitle("Honeywell HPMA115S0") + theme(plot.title = element_text(hjust = 0.5))+facet_grid(~source,scales = "free_x")+  theme(panel.spacing = unit(0, "lines")) +
  theme(plot.margin = unit(c(0,0,0,0), "lines"))

legend_ops_3 <- get_legend(p_ops_3)
legend_ops_4_7 <- get_legend(p_ops_4_7)

legend_p_pms <- get_legend(p_pms)
legend_p_opcr1 <- get_legend(p_opcr1)
legend_p_sps <- get_legend(p_sps)
legend_p_sds <- get_legend(p_sds)
legend_p_hpma <- get_legend(p_hpma)

label_ops_3<-p_ops_3$labels$y
label_ops_4_7 <-p_ops_4_7$labels$y
label_p_pms <- p_pms$labels$y


p_ops_3 <- p_ops_3+theme(legend.position = "none") + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_ops_4_7 <- p_ops_4_7+theme(legend.position = "none") + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_nano <- p_nano+theme(legend.position = "none") + theme(axis.title.x=element_blank(), axis.title.y=element_blank())


p_pms <- p_pms+theme(legend.position = "none")+ theme(axis.title.y=element_blank())
p_opcr1 <- p_opcr1+theme(legend.position = "none")+ theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_sps <- p_sps+theme(legend.position = "none")+ theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_sds <- p_sds+theme(legend.position = "none")+ theme(axis.title.x=element_blank(), axis.title.y=element_blank())
p_hpma <- p_hpma+theme(legend.position = "none")+ theme(axis.title.x=element_blank(), axis.title.y=element_blank())


pl_assembled<-plot_grid(p_ops_3, p_ops_4_7, p_nano, 
             p_hpma, p_opcr1,p_sds,p_sps, p_pms,
             nrow=8, align = "v", rel_heights = c(0.2, 0.2, 0.2, 0.4, 0.4, 0.4, 0.4,0.4)
             , labels=c("(a)", "(b)", "(c)", "(d)", "(e)", "(f)", "(g)", "(h)"),label_size = 10 )

pl_assembled
pl_assembled_legend<-plot_grid(legend_ops_3, legend_ops_4_7, legend_p_hpma, legend_p_opcr1, legend_p_sds, legend_p_sps, legend_p_pms,nrow=3,ncol=3 )


ggsave(pl_assembled,filename = "time_series_no_enclosure_exp_5.svg", height = 14, width = 8)

pl_assembled_legend
ggsave(pl_assembled_legend, filename = "time_series_no_enclosure_exp_5_legend.svg", height = 14, width = 8)

```
