---
title: "RH and temperature from DHT22"
output: html_notebook
---

This notebook explores the relative humidity and the temperature measured by the DHT22 sensor.


```{r setup}

source("utilities.R")
source("variables.R")
require(ggforce)
require(dplyr)
require(ggplot2)
require(plotly)
df_rht<-read.csv("C:/Data/LabStudy/20190905NoEnclosureRH23C/twiglet/port27_aggregated.move",header=FALSE)
names(df_rht)<-c("date", "rh", "temperature")

df_rht<-df_rht %>%
  mutate(date = as.POSIXct(date, tz= "UTC"))

df<-readRDS(sensor_file)

df_sht <- df %>%
  filter(sensor == "SHT35") %>%
  filter(date>=as.POSIXct("2019-09-05 07:00:00", tz = "UTC"), date<=as.POSIXct("2019-09-05 20:00:00", tz = "UTC"))

```


```{r}



p<-df_rht %>%
  filter(rh>=50) %>%
  filter(date >= as.POSIXct("2019-09-05 07:00:00", tz="UTC"), date<= as.POSIXct("2019-09-05 12:33:49", tz = "UTC")) %>%
  ggplot()+
  annotate("rect", xmin = as.POSIXct("2019-09-05 07:44:21",tz="UTC"), xmax = as.POSIXct("2019-09-05 08:02:33", tz="UTC"),   ymin = -Inf, ymax = +Inf,   fill = "#66C2A5", alpha=0.2) +
  annotate("rect", xmin = as.POSIXct("2019-09-05 08:02:33",tz="UTC"), xmax = as.POSIXct("2019-09-05 08:18:20", tz="UTC"),   ymin = -Inf, ymax = +Inf,   fill = "#FC8D62", alpha=0.2) +
  annotate("rect", xmin = as.POSIXct("2019-09-05 09:24:27",tz="UTC"), xmax = as.POSIXct("2019-09-05 09:42:43", tz="UTC"),   ymin = -Inf, ymax = +Inf,   fill = "#66C2A5", alpha=0.2) +
  annotate("rect", xmin = as.POSIXct("2019-09-05 09:43:12",tz="UTC"), xmax = as.POSIXct("2019-09-05 09:56:10", tz="UTC"),   ymin = -Inf, ymax = +Inf,   fill = "#FC8D62", alpha=0.2) +
    annotate("rect", xmin = as.POSIXct("2019-09-05 10:17:58",tz="UTC"), xmax = as.POSIXct("2019-09-05 10:37:03", tz="UTC"),   ymin = -Inf, ymax = +Inf,   fill = "#66C2A5", alpha=0.2) +
  annotate("rect", xmin = as.POSIXct("2019-09-05 10:37:03",tz="UTC"), xmax = as.POSIXct("2019-09-05 10:52:00", tz="UTC"),   ymin = -Inf, ymax = +Inf,   fill = "#FC8D62", alpha=0.2) +
      annotate("rect", xmin = as.POSIXct("2019-09-05 11:06:38",tz="UTC"), xmax = as.POSIXct("2019-09-05 11:22:33", tz="UTC"),   ymin = -Inf, ymax = +Inf,   fill = "#66C2A5", alpha=0.2) +
  annotate("rect", xmin = as.POSIXct("2019-09-05 11:22:33",tz="UTC"), xmax = as.POSIXct("2019-09-05 11:34:53", tz="UTC"),   ymin = -Inf, ymax = +Inf,   fill = "#FC8D62", alpha=0.2) +
        annotate("rect", xmin = as.POSIXct("2019-09-05 11:56:21",tz="UTC"), xmax = as.POSIXct("2019-09-05 12:15:04", tz="UTC"),   ymin = -Inf, ymax = +Inf,   fill = "#66C2A5", alpha=0.2) +
  annotate("rect", xmin = as.POSIXct("2019-09-05 12:15:04",tz="UTC"), xmax = as.POSIXct("2019-09-05 12:33:34", tz="UTC"),   ymin = -Inf, ymax = +Inf,   fill = "#FC8D62", alpha=0.2) +
  geom_line(aes(x=date, y = rh,color = "DHT22")) +
  geom_line(data = df_sht, aes(x= date, y=humidity,group=site,colour=site))+ylab("Relative humidity (%)")+theme_bw()+theme(legend.position = "none") + theme(axis.title.x=element_blank())

p
ggsave(filename = "evolution_rh_SHT35_DHT22.svg",plot = p)
```

```{r}

require(forcats)
x<-factor(df_sht$site)
#df2$exp<-fct_recode(x, "(1) RH=55.6% - T=25.9C" = "RH55 T23C 05092019", "(2) RH=68.5% - T=28.2C" = "RH75 T23C 05092019", "(3) RH=72.0% - T=28.5C" ="RH80 T23C 05092019", "(4) RH=75.6% - T=28.6C" = "RH85 T23C 05092019", "(5) RH=78.5% - T=28.7C" = "RH90 T23C 05092019")

df_sht$site<-fct_recode(x, "SHT35 lab-1" = "lab-1", "SHT35 lab-2" = "lab-2", "SHT35 lab-3" ="lab-3", "SHT35 lab-4" = "lab-4")

p_temp<-df_rht %>%
   filter(date >= as.POSIXct("2019-09-05 07:00:00", tz="UTC"), date<= as.POSIXct("2019-09-05 12:33:49", tz = "UTC")) %>%
  ggplot()+
  annotate("rect", xmin = as.POSIXct("2019-09-05 07:44:21",tz = "UTC"), xmax = as.POSIXct("2019-09-05 08:02:33", tz = "UTC"),   ymin = -Inf, ymax = +Inf,   fill = "#66C2A5", alpha=0.2) +
  annotate("rect", xmin = as.POSIXct("2019-09-05 08:02:33",tz = "UTC"), xmax = as.POSIXct("2019-09-05 08:18:20", tz = "UTC"),   ymin = -Inf, ymax = +Inf,   fill = "#FC8D62", alpha = 0.2) +
  annotate("rect", xmin = as.POSIXct("2019-09-05 09:24:27",tz = "UTC"), xmax = as.POSIXct("2019-09-05 09:42:43", tz = "UTC"),   ymin = -Inf, ymax = +Inf,   fill = "#66C2A5", alpha = 0.2) +
  annotate("rect", xmin = as.POSIXct("2019-09-05 09:43:12",tz="UTC"), xmax = as.POSIXct("2019-09-05 09:56:10", tz = "UTC"),   ymin = -Inf, ymax = +Inf,   fill = "#FC8D62", alpha = 0.2) +
    annotate("rect", xmin = as.POSIXct("2019-09-05 10:17:58",tz = "UTC"), xmax = as.POSIXct("2019-09-05 10:37:03", tz = "UTC"),   ymin = -Inf, ymax = +Inf,   fill = "#66C2A5", alpha = 0.2) +
  annotate("rect", xmin = as.POSIXct("2019-09-05 10:37:03",tz="UTC"), xmax = as.POSIXct("2019-09-05 10:52:00", tz = "UTC"),   ymin = -Inf, ymax = +Inf,   fill = "#FC8D62", alpha=0.2) +
      annotate("rect", xmin = as.POSIXct("2019-09-05 11:06:38",tz="UTC"), xmax = as.POSIXct("2019-09-05 11:22:33", tz="UTC"),   ymin = -Inf, ymax = +Inf,   fill = "#66C2A5", alpha=0.2) +
  annotate("rect", xmin = as.POSIXct("2019-09-05 11:22:33",tz="UTC"), xmax = as.POSIXct("2019-09-05 11:34:53", tz = "UTC"),   ymin = -Inf, ymax = +Inf,   fill = "#FC8D62", alpha=0.2) +
        annotate("rect", xmin = as.POSIXct("2019-09-05 11:56:21",tz="UTC"), xmax = as.POSIXct("2019-09-05 12:15:04", tz="UTC"),   ymin = -Inf, ymax = +Inf,   fill = "#66C2A5", alpha=0.2) +
  annotate("rect", xmin = as.POSIXct("2019-09-05 12:15:04",tz="UTC"), xmax = as.POSIXct("2019-09-05 12:33:34", tz = "UTC"),   ymin = -Inf, ymax = +Inf,   fill = "#FC8D62", alpha=0.2) +
  geom_line(aes(x = date, y = temperature, color = "DHT22")) +
  geom_line(data = df_sht, aes(x= date, y = temperature, group = site, colour = site)) +  xlab("Time") +
ylab(expression('Temperature ('*~degree*C*')'))+theme_bw()+theme(legend.position = "bottom", legend.title = )

p_pm_legend <- get_legend(p_temp)
require(cowplot)
pl_assembled<-plot_grid(p,p_temp,align = "v",ncol = 1)
ggsave(plot = pl_assembled, filename = "evolution_rht_SHT35_DHT22.svg")
```

```{r}

max(df_rht$rh,na.rm=TRUE)
max(df_sht$humidity,na.rm=TRUE)

df_sht %>%
   filter(date >= as.POSIXct("2019-09-05 07:00:00", tz="UTC"), date<= as.POSIXct("2019-09-05 12:33:49", tz = "UTC")) %>%
  group_by(date) %>%
  summarise(min = min(humidity, na.rm = TRUE), max = max(humidity, na.rm = TRUE)) %>%
  mutate(diff = max-min) -> tmp

tmp %>%
  summarise(mean(diff, na.rm = TRUE), min(diff, na.rm = TRUE), max(diff, na.rm = TRUE),quantile(diff, na.rm = TRUE, probs = c(0.1)), quantile(diff, na.rm = TRUE, probs = c(0.9)),2*sd(diff, na.rm = TRUE))
hist(tmp$diff)
tmp %>%
  ggplot() + geom_point(aes(x=date, y = diff))

```